---
# Tasks for 'hardware' role

# --- GPU Specific Hardware Acceleration ---
- name: Hardware | Install intel media drivers
  ansible.builtin.dnf:
    name: "{{ intel_media_packages }}"
    state: present
  when: is_intel
  tags: [hardware, intel]

- name: Hardware | Install AMD VA-API and VDPAU (Freeworld)
  ansible.builtin.dnf:
    name: "{{ amd_multimedia_packages }}"
    state: present
    allowerasing: true
  when: is_amd
  tags: [hardware, amd]

# --- Multimedia Codecs & FFmpeg Swap ---
- name: Codecs | Swap ffmpeg-free for full ffmpeg (RPM Fusion)
  ansible.builtin.dnf:
    name: ffmpeg
    allowerasing: yes
    state: present
  tags: [hardware, codecs, ffmpeg]

- name: Codecs | Install Multimedia Group and Codecs
  ansible.builtin.dnf:
    name: "{{ multimedia_packages }}"
    state: present
    update_cache: yes
  tags: [hardware, codecs, multimedia]
